export type {
  Layer,
  LayerKind,
  BorderBoxProperties,
  TextBlockProperties,
  FigletTextProperties,
  ImageProperties,
  EdgePathProperties,
  ComponentInstanceProperties,
  CustomBorderChars,
  AutoLayoutConfig,
  LayerProperties,
  RuntimeRole,
  RuntimeComponentKind,
  RuntimeAction,
  RegionShape,
  RuntimeBindingRef,
  RuntimeInteractionRef,
  RuntimeProvenance,
  SemanticRegion,
  PageRuntimeSemantics,
  DocumentRuntimeSemantics,
  FIGMIIPage,
  FIGMIIDocument,
  ComponentDef,
  PageRuntimeMetadata,
  FigMeRuntimeMetadata,
} from './types.ts'
export type { LayerRuntimeMetadata } from '@primitives/runtime-semantics/types.ts'
export {
  DOCUMENT_SCHEMA_VERSION,
  RUNTIME_ROLES,
  RUNTIME_TIER_1_COMPONENT_KINDS,
  RUNTIME_TIER_2_COMPONENT_KINDS,
  RUNTIME_COMPONENT_KINDS,
} from './types.ts'
export {
  addLayer,
  removeLayer,
  updateLayer,
  addRegion,
  updateRegion,
  removeRegion,
  updateRegionShape,
  updatePageRuntime,
  updateDocumentRuntime,
  moveLayer,
  reorderLayers,
  addPage,
  removePage,
  setActivePage,
  createComponent,
  instantiateComponent,
  detachComponent,
  createEmptyDocument,
  createEmptyPage,
  groupLayers,
  ungroupLayers,
  bringForward,
  sendBackward,
  bringToFront,
  sendToBack,
  moveLayerToGroup,
} from './operations.ts'
export {
  flattenLayerOrder,
  isEffectivelyLocked,
  isEffectivelyHidden,
  getDepth,
} from './hierarchy.ts'
export {
  getPageCanvasSizeInfo,
  applyPageCanvasSizeToGridConfig,
  getVisiblePageContentBounds,
} from './canvasSize.ts'
export { serializeDocument, deserializeDocument, migrateDocument } from './serialization.ts'
export type { ColorOverrideMap } from './colorOverrides.ts'
export { computeColorOverrides } from './colorOverrides.ts'
