export type {
  Layer,
  LayerKind,
  BorderBoxProperties,
  TextBlockProperties,
  FigletTextProperties,
  ImageProperties,
  EdgePathProperties,
  ComponentInstanceProperties,
  CustomBorderChars,
  AutoLayoutConfig,
  LayerProperties,
  FigMePage,
  FigMeDocument,
  ComponentDef,
} from './types.ts'
export {
  addLayer,
  removeLayer,
  updateLayer,
  moveLayer,
  reorderLayers,
  addPage,
  removePage,
  setActivePage,
  createComponent,
  instantiateComponent,
  detachComponent,
  createEmptyDocument,
  createEmptyPage,
} from './operations.ts'
export { serializeDocument, deserializeDocument } from './serialization.ts'
